name: Terraform Plan
on:
  workflow_dispatch:
permissions: read-all      
jobs:
  plan:
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY}}
         AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

 
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
         tflint_version: v0.50.3
 
  
      - name: Running Tflint
        run: tflint -f compact
        continue-on-error: true
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
         version: latest
 
      - name: Run OPA Tests
        run: opa test . || true
 
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          soft_fail: true 


      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -out=tfplan
